// Code generated by lister-gen. DO NOT EDIT.

package v1

// HouseListerExpansion allows custom methods to be added to
// HouseLister.
type HouseListerExpansion interface{}

// HouseNamespaceListerExpansion allows custom methods to be added to
// HouseNamespaceLister.
type HouseNamespaceListerExpansion interface{}
