// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/slok/kubewebhook/v2/test/integration/crd/apis/building/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// HouseLister helps list Houses.
// All objects returned here must be treated as read-only.
type HouseLister interface {
	// List lists all Houses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.House, err error)
	// Houses returns an object that can list and get Houses.
	Houses(namespace string) HouseNamespaceLister
	HouseListerExpansion
}

// houseLister implements the HouseLister interface.
type houseLister struct {
	listers.ResourceIndexer[*v1.House]
}

// NewHouseLister returns a new HouseLister.
func NewHouseLister(indexer cache.Indexer) HouseLister {
	return &houseLister{listers.New[*v1.House](indexer, v1.Resource("house"))}
}

// Houses returns an object that can list and get Houses.
func (s *houseLister) Houses(namespace string) HouseNamespaceLister {
	return houseNamespaceLister{listers.NewNamespaced[*v1.House](s.ResourceIndexer, namespace)}
}

// HouseNamespaceLister helps list and get Houses.
// All objects returned here must be treated as read-only.
type HouseNamespaceLister interface {
	// List lists all Houses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.House, err error)
	// Get retrieves the House from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.House, error)
	HouseNamespaceListerExpansion
}

// houseNamespaceLister implements the HouseNamespaceLister
// interface.
type houseNamespaceLister struct {
	listers.ResourceIndexer[*v1.House]
}
