// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/slok/kubewebhook/v2/test/integration/crd/client/clientset/versioned/typed/building/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeBuildingV1 struct {
	*testing.Fake
}

func (c *FakeBuildingV1) Houses(namespace string) v1.HouseInterface {
	return &FakeHouses{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeBuildingV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
