// Code generated by mockery v1.0.0
package webhook

import mock "github.com/stretchr/testify/mock"
import v1beta1 "k8s.io/api/admission/v1beta1"

// Webhook is an autogenerated mock type for the Webhook type
type Webhook struct {
	mock.Mock
}

// Review provides a mock function with given fields: ar
func (_m *Webhook) Review(ar *v1beta1.AdmissionReview) *v1beta1.AdmissionResponse {
	ret := _m.Called(ar)

	var r0 *v1beta1.AdmissionResponse
	if rf, ok := ret.Get(0).(func(*v1beta1.AdmissionReview) *v1beta1.AdmissionResponse); ok {
		r0 = rf(ar)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.AdmissionResponse)
		}
	}

	return r0
}
