// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	buildingv1 "github.com/slok/kubewebhook/v2/test/integration/crd/apis/building/v1"
	versioned "github.com/slok/kubewebhook/v2/test/integration/crd/client/clientset/versioned"
	internalinterfaces "github.com/slok/kubewebhook/v2/test/integration/crd/client/informers/externalversions/internalinterfaces"
	v1 "github.com/slok/kubewebhook/v2/test/integration/crd/client/listers/building/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HouseInformer provides access to a shared informer and lister for
// Houses.
type HouseInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.HouseLister
}

type houseInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHouseInformer constructs a new informer for House type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHouseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHouseInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHouseInformer constructs a new informer for House type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHouseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BuildingV1().Houses(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BuildingV1().Houses(namespace).Watch(context.TODO(), options)
			},
		},
		&buildingv1.House{},
		resyncPeriod,
		indexers,
	)
}

func (f *houseInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHouseInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *houseInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&buildingv1.House{}, f.defaultInformer)
}

func (f *houseInformer) Lister() v1.HouseLister {
	return v1.NewHouseLister(f.Informer().GetIndexer())
}
