// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"net/http"

	v1 "github.com/slok/kubewebhook/v2/test/integration/crd/apis/building/v1"
	"github.com/slok/kubewebhook/v2/test/integration/crd/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type BuildingV1Interface interface {
	RESTClient() rest.Interface
	HousesGetter
}

// BuildingV1Client is used to interact with features provided by the building.kubewebhook.slok.dev group.
type BuildingV1Client struct {
	restClient rest.Interface
}

func (c *BuildingV1Client) Houses(namespace string) HouseInterface {
	return newHouses(c, namespace)
}

// NewForConfig creates a new BuildingV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*BuildingV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new BuildingV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*BuildingV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &BuildingV1Client{client}, nil
}

// NewForConfigOrDie creates a new BuildingV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *BuildingV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new BuildingV1Client for the given RESTClient.
func New(c rest.Interface) *BuildingV1Client {
	return &BuildingV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *BuildingV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
